/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.edu.ups.vista.factura;

import ec.edu.ups.controladores.ControladorFacturaDetalle;
import ec.edu.ups.controladores.ControladorProducto;
import ec.edu.ups.modelo.FacturaDetalle;
import ec.edu.ups.modelo.Producto;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author José Quinde
 */
public class VentanaAgregarDetalle extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaAgregarDetalle
     */
    //Declaracion de Variables
    private ControladorFacturaDetalle controladorFacturaDetalle;
    private ControladorProducto controladorProducto;
    private Set<Producto> listaProductos;
    private Locale localizacion;
    private static ResourceBundle mensajes;
    double subTotal;
    int indice=0;
    /**
     * Constructor que inicializa los componentes
     * @param controladorFacturaDetalle
     * @param controladorProducto 
     */
    public VentanaAgregarDetalle(ControladorFacturaDetalle controladorFacturaDetalle,ControladorProducto controladorProducto) {
        initComponents();
        this.controladorFacturaDetalle=controladorFacturaDetalle;
        this.controladorProducto=controladorProducto;
        txtCodigo.setText(String.valueOf(this.controladorFacturaDetalle.getCodigo()));
        listaProductos= controladorProducto.getLista();
        for (Producto producto : listaProductos) {
            cbxProducto.addItem(producto.getNombre());            
        }
   productoBuscado();
    }
    /**
     * Metodo que cambia el idioma de todo El jInternalFrame
     * @param localizacion 
     */
   public static void cambiarIdioma(Locale localizacion){
         mensajes=ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes",Locale.getDefault());
         labelCod.setText(mensajes.getString("cliente.codigo"));
         labelPro.setText(mensajes.getString("producto.nombre"));
         labelPrecio.setText(mensajes.getString("producto.precioUnitario"));
         lblCantidad.setText(mensajes.getString("detalle.cantidad"));
         btnCalcularSubTotal.setText(mensajes.getString("boton.CalSub"));
         btnAnadirCesta.setText(mensajes.getString("boton.añaPro"));
   }
   /**
    * Este metodo setea el precio del producto selecciona en el jcombobox
    */
    public void productoBuscado(){
        Producto producto = buscarProducto();
        txtPrecioUnitario.setText(String.valueOf(producto.getPrecio()));
    }
    /**
     * Este metodo retorna el producto del jcombox dependiendo la seleccion
     * @return 
     */
     public Producto buscarProducto() {
        Producto l = new Producto();
        for (Producto producto : listaProductos) {
            if (cbxProducto.getSelectedItem().toString().equalsIgnoreCase(producto.getNombre())) {
                l = producto;
            }
        }
        return l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnadirCesta = new javax.swing.JButton();
        btnCalcularSubTotal = new javax.swing.JButton();
        cbxProducto = new javax.swing.JComboBox();
        labelPro = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        labelCod = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Producto");

        btnAnadirCesta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAnadirCesta.setText("Añadir Producto");
        btnAnadirCesta.setEnabled(false);
        btnAnadirCesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirCestaActionPerformed(evt);
            }
        });

        btnCalcularSubTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCalcularSubTotal.setText("Calcular Sub Total");
        btnCalcularSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularSubTotalActionPerformed(evt);
            }
        });

        cbxProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxProducto.setForeground(new java.awt.Color(0, 0, 204));
        cbxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductoActionPerformed(evt);
            }
        });

        labelPro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPro.setText("Producto");

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSubTotal.setText("Sub Total:");

        txtCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 0, 204));

        lblCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCantidad.setText("Cantidad: ");
        lblCantidad.setToolTipText("");

        labelPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPrecio.setText("Precio Unitario:");

        txtPrecioUnitario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPrecioUnitario.setForeground(new java.awt.Color(0, 0, 204));

        txtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubTotal.setForeground(new java.awt.Color(0, 0, 204));
        txtSubTotal.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txtSubTotal.setEnabled(false);
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        txtCodigo.setEnabled(false);

        labelCod.setText("Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnAnadirCesta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcularSubTotal)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecio)
                            .addComponent(lblCantidad)
                            .addComponent(lblSubTotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSubTotal)
                            .addComponent(txtCantidad)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPro)
                            .addComponent(labelCod))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCod))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPro)
                    .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotal)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadirCesta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirCestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirCestaActionPerformed
        //Añade un detalle a la factura
        Producto producto = buscarProducto();
        FacturaDetalle facturaDetalle=new FacturaDetalle();
        facturaDetalle.setPrecio(Double.parseDouble(txtPrecioUnitario.getText()));
        facturaDetalle.setCantidad(Integer.parseInt(txtCantidad.getText()));
        facturaDetalle.setSubtotal(Double.parseDouble(txtSubTotal.getText()));
        facturaDetalle.setProducto(producto);
        facturaDetalle.setCodigoFactura(VentanaAgregarFactura.codigoFac);
       controladorFacturaDetalle.crear(facturaDetalle);
       Object[] fila = {facturaDetalle.getCodigo(), producto.getNombre(), facturaDetalle.getPrecio(), facturaDetalle.getCantidad(), facturaDetalle.getSubtotal()};
        VentanaAgregarFactura.modeloTabla.addRow(fila);
        JOptionPane.showMessageDialog(this, "Se ha ingresado el Producto","Añadir Producto",JOptionPane.OK_OPTION);
        //Setear codigo
        //vaciar Txts
        txtCodigo.setText(String.valueOf(this.controladorFacturaDetalle.getCodigo()));
        txtCantidad.setText("");
        txtSubTotal.setText("");
      btnAnadirCesta.setEnabled(false);
   
    }//GEN-LAST:event_btnAnadirCestaActionPerformed

    private void btnCalcularSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularSubTotalActionPerformed
        //Calcula el SubTotal del Detalle multiplicando la cantidad por el precio
        if (txtPrecioUnitario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Error Ingrese el Precio Unitario");
        } else if (txtCantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Error Ingrese la Cantidad");
        } else {
            subTotal = (Double.parseDouble(txtPrecioUnitario.getText())) * (Double.parseDouble(txtCantidad.getText()));
            txtSubTotal.setText(String.valueOf(subTotal));
            btnAnadirCesta.setEnabled(true);
        }
    }//GEN-LAST:event_btnCalcularSubTotalActionPerformed

    private void cbxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductoActionPerformed
        //Selecciona el producto dependiendo la opcion escojida en el jcomboBox
        productoBuscado();
    }//GEN-LAST:event_cbxProductoActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAnadirCesta;
    public static javax.swing.JButton btnCalcularSubTotal;
    private javax.swing.JComboBox cbxProducto;
    public static javax.swing.JLabel labelCod;
    public static javax.swing.JLabel labelPrecio;
    public static javax.swing.JLabel labelPro;
    public static javax.swing.JLabel lblCantidad;
    public static javax.swing.JLabel lblSubTotal;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtSubTotal;
    // End of variables declaration//GEN-END:variables
}
