/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.edu.ups.vista.cliente;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author José Quinde
 */
public class VentanaListarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaListarClientes
     */
    //Declaracion de Variables
    private ControladorCliente controladorCliente;
    private Locale localizacion;
    private static ResourceBundle mensajes;
    public static DefaultTableModel modelo;
    /**
     * Constructor que inicializa los componentes
     * @param controladorCliente 
     */
    public VentanaListarClientes(ControladorCliente controladorCliente) {
        initComponents();
        this.controladorCliente=controladorCliente;
        modelo = new DefaultTableModel();
        //Ingresa los nombres de las columnas
        Object[] columnas = {"Codigo","Nombre","Cedula","Direccion","Telefono"};
        modelo.setColumnIdentifiers(columnas);
        tblCliente.setModel(modelo);
        llenarDatos();
    }
    
    /**
     * Metodo que cambia el idioma de todo El jInternalFrame
     * @param localizacion 
     */
    public static void cambiarIdioma(Locale localizacion){
        mensajes=ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes",Locale.getDefault());
        Object[] columnas = {mensajes.getString("cliente.codigo"),mensajes.getString("cliente.nombre"), mensajes.getString("cliente.cedula"),mensajes.getString("cliente.direccion"), mensajes.getString("cliente.telefono")};
        modelo.setColumnIdentifiers(columnas);
    }
    /**
     * Este Metodo llena los datos de la tabla con la lista de Clientes
     */
    public void llenarDatos(){
       
         Set <Cliente> lista= controladorCliente.getLista();
        for (Cliente cliente: lista){
            Object[] datos={cliente.getCodigo(),
            cliente.getNombre(),
            cliente.getCedula(),
            cliente.getDireccion(),
            cliente.getTelefono()};
            modelo.addRow(datos);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Listar Clientes");

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cedula", "Direccion", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
